import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import test from 'node:test'; import { readBaselineSource } from './support/readBaselineSource.mjs';
async function setup(state='Leaving',cargo={}){const [x,s,c,e,r,k]=await Promise.all([import('../src/exits/index.ts'),import('../src/ships/index.ts'),import('../src/config/validateConfigSource.ts'),import('../src/core/DomainEventQueue.ts'),import('../src/routes/index.ts'),import('../src/core/FixedStepClock.ts')]);const b=c.validateConfigSource(readBaselineSource()),q=new e.DomainEventQueue(),zones=x.createExitZones(b.levels.calm_01),m=new s.ShipModel({id:'ship',characteristics:s.createShipCharacteristicsRegistry(b).require('speedboat'),position:{x:20,y:500},rotationDeg:0,state:s.ShipState[state],cargo}),sys=new x.ExitSystem({zones,score:x.createExitScore(b),events:q});return{x,s,c,e,r,k,b,q,zones,m,sys};}
test('real calm_01 enabled exit zones preserve machine fields',async()=>{const a=await setup();assert.deepEqual(a.zones.map(z=>z.id),['exit_left','exit_right','exit_bottom']);assert.deepEqual(a.zones[0],{id:'exit_left',x:20,y:500,width:40,height:900,edge:'left'});});
test('disabled exit zones are ignored',async()=>{const a=await setup();const level=structuredClone(a.b.levels.calm_01);level.layout.blocks.push({blockType:'exit_zone',id:'off',x:0,y:0,enabled:false,props:{width:1,height:1,edge:'left'}});assert.equal(a.x.createExitZones(level).some(z=>z.id==='off'),false);});
test('rectangle boundaries are inclusive',async()=>{const a=await setup();a.m.setPositionXY(40,50);assert.deepEqual(a.sys.step([a.m]).pendingShipIds,['ship']);});
test('ReadyToLeave inside exit does not auto-exit',async()=>{const a=await setup('ReadyToLeave');const r=a.sys.step([a.m]);assert.equal(r.scoreDelta,0);assert.deepEqual(r.pendingShipIds,[]);});
test('RouteCommitService transitions ReadyToLeave to Leaving',async()=>{const a=await setup('ReadyToLeave');const svc=new a.r.RouteCommitService({navigation:new a.r.NavigationValidator([]),config:a.r.createRouteProcessingConfig(a.b)});assert.equal(svc.commit({ship:a.m,draft:{shipId:'ship',points:[{x:100,y:500}]}}).kind,'committed');assert.equal(a.m.state,'Leaving');});
test('Leaving outside has no pending, first entry pending, next step finalizes',async()=>{const a=await setup();a.m.setPositionXY(500,500);assert.deepEqual(a.sys.step([a.m]).pendingShipIds,[]);a.m.setPositionXY(20,500);assert.deepEqual(a.sys.step([a.m]).pendingShipIds,['ship']);const r=a.sys.step([]);assert.deepEqual(r.despawnedShipIds,['ship']);assert.equal(r.scoreDelta,a.x.createExitScore(a.b));});
test('pending survives outside move and duplicate input, then emits once',async()=>{const a=await setup(),got=[];a.q.subscribe('ship_exited',v=>got.push(v));assert.deepEqual(a.sys.step([a.m,a.m]).pendingShipIds,['ship']);a.m.setPositionXY(500,500);const r=a.sys.step([]);a.q.flush();assert.equal(got.length,1);assert.deepEqual(got[0],{shipId:'ship',shipType:'speedboat',scoreDelta:a.x.createExitScore(a.b)});assert.equal(a.sys.step([a.m]).scoreDelta,0);assert.deepEqual(r.despawnedShipIds,['ship']);});
test('cargo rejection clears route once and rearms only after all exits are left',async()=>{const a=await setup('Leaving',{general:1});a.m.replaceRoute(new a.s.ShipRoute([{x:100,y:500}]));assert.deepEqual(a.sys.step([a.m]).rejectedCargoShipIds,['ship']);a.m.replaceRoute(new a.s.ShipRoute([{x:100,y:500}]));assert.deepEqual(a.sys.step([a.m]).rejectedCargoShipIds,[]);assert.notEqual(a.m.route,null);a.m.setPositionXY(500,500);a.sys.step([a.m]);a.m.setPositionXY(20,500);assert.deepEqual(a.sys.step([a.m]).rejectedCargoShipIds,['ship']);});
test('zero cargo is empty and invalid pending states cancel',async()=>{const a=await setup('Leaving',{general:0});assert.equal(a.m.cargoTotal,0);a.sys.step([a.m]);a.m.setState(a.s.ShipState.Destroyed);assert.equal(a.sys.step([]).scoreDelta,0);const b=await setup();b.sys.step([b.m]);b.m.setState(b.s.ShipState.Navigating);assert.equal(b.sys.step([]).scoreDelta,0);});
test('30 60 120 fixed clock exit outcomes match',async()=>{const run=async fps=>{const a=await setup(),out=[];a.q.subscribe('ship_exited',v=>out.push(v));const clock=new a.k.FixedStepClock({fixedHz:60,maxCatchUpSteps:6});for(let i=0;i<fps;i++)clock.advance(1000/fps,()=>a.sys.step([a.m]));a.q.flush();return{out,state:a.m.state};};const[a,b,c]=await Promise.all([run(30),run(60),run(120)]);assert.deepEqual(b,a);assert.deepEqual(c,a);});
test('production exit domain has no forbidden or level-specific dependency',()=>{const t=readFileSync('src/exits/ExitSystem.ts','utf8');assert.doesNotMatch(t,/Math\.random|Phaser|Yandex|calm_01|exit_left|\b980\b/);});
